route:
  group_by: [ alertname ]
  receiver: 'telepush' # default receiver
  repeat_interval: 24h

  routes:
    - receiver: 'telepush'
      repeat_interval: 12h
      matchers:
        - severity="high"

receivers:
- name: 'telepush'
  webhook_configs:
  - url: 'https://telepush.dev/api/inlets/alertmanager/7ee287'
