groups:
  - name: DemoAlerts
    rules:

      - alert: InstanceDownCritical
        expr: probe_success < 1
        for: 1m
        labels:
          severity: high
        annotations:
          summary: 'Alert with high severity.'
