scrape_configs:

- job_name: prometheus
  scrape_interval: 1s
  static_configs:
  - targets:
    - prometheus:9090

- job_name: blackbox
  metrics_path: /probe
  scrape_interval: 1s
  params:
    module: [http_2xx]
  static_configs:
  - targets:
    - prometheus:9090
    - web:5000/redis-client
    - grafana:3000
  relabel_configs:
  - source_labels: [__address__]
    target_label: __param_target
  - source_labels: [__param_target]
    target_label: instance
  - target_label: __address__
    replacement: blackbox:9115

- job_name: blackbox_tcp
  metrics_path: /probe
  scrape_interval: 1s
  params:
    module: [tcp_connect]
  static_configs:
  - targets:
    - redis:6379
  relabel_configs:
  - source_labels: [__address__]
    target_label: __param_target
  - source_labels: [__param_target]
    target_label: instance
  - target_label: __address__
    replacement: blackbox:9115

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: [ 'alertmanager:9093' ]

rule_files:
  - alert.yml
